---
- name: Download Redmine
  command: wget https://www.redmine.org/releases/redmine-3.4.4.tar.gz ; tar -zxvf redmine-3.4.4.tar.gz ; mv redmine-3.4.4 redmine

- name: Database configuration
  template: src=database.yml dest=/data/redmine/redmine/config/database.yml


- name: Install bundler
  command: cd /data/redmine/redmine ;  gem install bundler

- name: Install Ruby Dependencies
  command: cd /data/redmine/redmine ; bundle install --without development test

- name:  use Rake to start the server
  command: bundle exec rake generate_secret_token ; RAILS_ENV=production bundle exec rake db:migrate ; RAILS_ENV=production bundle exec rake redmine:load_default_data
  notify: restart nginx

- name: Change permission
  command: chown redmine:redmine /data/redmine -R
