---
- name: Install the Passenger PGP key and HTTPS support for the package manager
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  sudo: yes
  with_items:
    - dirmngr 
    - gnupg

- name: Add Key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 ; apt install -y apt-transport-https ca-certificates ; sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list' ; sudo apt update

- name: Install passenger and nginx
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - nginx-extras
    - passenger

- name: Remove nginx default conf
  command: rm -f /etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: copy Redmine conf 
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: nginx service state
  service: name=nginx state=started enabled=yes


