---
- name: Install the Passenger PGP key and HTTPS support for the package manager
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  sudo: yes
  with_items:
    - dirmngr 
    - gnupg

- name: Remove nginx default conf
  command: rm -f /etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: copy Redmine conf 
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: nginx service state
  service: name=nginx state=started enabled=yes


